// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_xqgjDwZ2ijRGXJjga4I2x4qTXaIQr5Y',
    appId: '1:62086654698:web:7021cd0cb2674e40db8593',
    messagingSenderId: '62086654698',
    projectId: 'iiumfirsteps',
    authDomain: 'iiumfirsteps.firebaseapp.com',
    storageBucket: 'iiumfirsteps.firebasestorage.app',
    measurementId: 'G-R1T6RJS1KM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiutAbPkT3BqYR0V9oWBt_tkaSMA1Lg9o',
    appId: '1:62086654698:android:77dd6bb596b2dc04db8593',
    messagingSenderId: '62086654698',
    projectId: 'iiumfirsteps',
    storageBucket: 'iiumfirsteps.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDg_GCM90V4gGssbWpCuoHWybIKlSDc7o',
    appId: '1:62086654698:ios:4356a4101e2d8ac4db8593',
    messagingSenderId: '62086654698',
    projectId: 'iiumfirsteps',
    storageBucket: 'iiumfirsteps.firebasestorage.app',
    iosBundleId: 'com.example.iiumfirststeps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDg_GCM90V4gGssbWpCuoHWybIKlSDc7o',
    appId: '1:62086654698:ios:4356a4101e2d8ac4db8593',
    messagingSenderId: '62086654698',
    projectId: 'iiumfirsteps',
    storageBucket: 'iiumfirsteps.firebasestorage.app',
    iosBundleId: 'com.example.iiumfirststeps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_xqgjDwZ2ijRGXJjga4I2x4qTXaIQr5Y',
    appId: '1:62086654698:web:8e0f29658d3fc918db8593',
    messagingSenderId: '62086654698',
    projectId: 'iiumfirsteps',
    authDomain: 'iiumfirsteps.firebaseapp.com',
    storageBucket: 'iiumfirsteps.firebasestorage.app',
    measurementId: 'G-SKD04PXTKQ',
  );
}
